### ISSUE TITLE
Feature Request: Verbose Output Option

### ISSUE THREAD

**Issue by The-Ducktor** [aedocw/epub2tts-edge#25]
## Description
Currently, the program only prints messages for new chapters or errors. It would be helpful to have a more verbose option for more accurate feedback, especially while processing long chapters.

## Proposal
Please consider adding a verbose mode that provides detailed updates during the program's execution such printing what on each paragraph processed. This would help users monitor progress more effectively, especially for lengthy chapters with like ~600 paragraphs by the or at least thats how many files it made a few times.

Thank you!

**Comment by aedocw** [comment]
This is a pretty good idea, and should be relatively easy to add. It won't be able to print as each sentence is being spoken since it tries to speak up to 10 at a time (per paragraph) in parallel, but I can have it output each paragraph as it gets to that point in the script.

**Comment by The-Ducktor** [comment]
it might also be nice try try out a progress bar while going through chapters similar to this
<img width="1467" alt="SCR-20240609-huvk" src="https://github.com/aedocw/epub2tts-edge/assets/130664593/c11d85d3-0d80-4f8f-a228-70d47cf2a173">

**Comment by aedocw** [comment]
I'm happy to merge your PR if you've got something already working :)

**Comment by The-Ducktor** [comment]
> I'm happy to merge your PR if you've got something already working :)

Sure but it's effectively just something that AI made in 5 seconds

**Comment by aedocw** [comment]
"something that AI made in 5 seconds" accounts for at least 50% of all the code in this repo haha!

**Comment by aedocw** [comment]
This has been resolved with the progress bar PR from @The-Ducktor - thanks!
