### ISSUE TITLE
Replace "shhh" with something more friendly to human ear

### ISSUE THREAD

**Issue by darauble** [aedocw/epub2tts-edge#33]
This is an annoying quirk of English language, but most of TTSs (including Edge) pronounce longer "shhhh" like /ˈɛs ˈeɪtʃ ˈeɪtʃˈeɪtʃ/. This could be demonstrated with simple:

`edge-playback -t '"Hey, shhhhh", she whispered.'`

Only `shh` is pronounced _correctly_ (whatever that means). So I suppose that in the book pre-processing (of course, with an optional switch on, like `--shhh`) all `shh+[^a-gi-z]` could be replaced with `shh`.

Just for record: I myself replace all `shhh+`s with `shush` in the exported text file, it is also read quite well by TTS.

**Comment by aedocw** [comment]
I think that's a good idea, but a text change like that would be up to the person making the audio book. I don't want epub2tts-edge changing the text for people...
